In [75]:
import h5py
import json
import numpy as np

In [39]:
with open('data1010.json', 'r') as File:
    data = json.load(File)

In [40]:
len(data)

1108

In [76]:
f = h5py.File("annot_data1010.h5", "w")

OSError: Unable to create file (unable to truncate a file which is already open)

In [45]:
bbox = f.create_dataset("bndbox", (len(data)*4, 1, 4,), dtype='i')
iname = f.create_dataset("imgname", (len(data)*4, 8, ), dtype='i')
pt = f.create_dataset("part", (len(data)*4, 4, 2,), dtype = 'i')

In [46]:
# Creating .h5 file
for i in range(len(data)):
    if(i != 152):
        #print(i)
        for j in range(4):
            ind = i*4+j
            d = data[i]['annotations'][j]
            d1 = data[i]['annotations'][4+j*4:8+j*4]
            bbox[ind] = [d['x'], d['y'], d['x']+d['width'], d['y']+d['height']][:]
            iname[ind] = [ord(x) for x in data[i]['filename']][:]
            pt[ind] = [[d1[k]['x'], d1[k]['y']] for k in range(4)][:]

In [47]:
for item in pt:
    print(item)

[[548 189]
 [502 180]
 [513 220]
 [435 221]]
[[595 269]
 [607 224]
 [570 232]
 [542 141]]
[[1011  308]
 [ 990  320]
 [1023  343]
 [ 911  415]]
[[749 556]
 [765 523]
 [730 515]
 [759 423]]
[[593 170]
 [541 164]
 [559 207]
 [470 212]]
[[597 270]
 [610 224]
 [576 228]
 [542 138]]
[[ 997  272]
 [ 986  294]
 [1025  302]
 [ 938  409]]
[[744 556]
 [769 528]
 [737 519]
 [763 421]]
[[612 156]
 [560 156]
 [581 200]
 [482 218]]
[[591 293]
 [610 247]
 [572 249]
 [550 143]]
[[1038  196]
 [1017  212]
 [1057  223]
 [ 986  337]]
[[747 559]
 [766 525]
 [737 518]
 [765 415]]
[[609 158]
 [554 161]
 [574 203]
 [478 219]]
[[596 322]
 [615 279]
 [578 277]
 [583 181]]
[[1081  181]
 [1058  182]
 [1090  207]
 [1013  305]]
[[747 562]
 [767 523]
 [736 519]
 [763 413]]
[[595 154]
 [546 165]
 [572 198]
 [479 217]]
[[581 338]
 [607 296]
 [570 292]
 [578 199]]
[[1119  152]
 [1097  165]
 [1129  190]
 [1016  270]]
[[745 560]
 [765 524]
 [736 519]
 [765 415]]
[[607 161]
 [567 152]
 [585 187]
 [478 220]]
[[625 331]
 [62

 [769 192]]
[[1088  459]
 [1087  431]
 [1066  451]
 [ 239  260]]
[[248 216]
 [208 221]
 [272 144]
 [189 382]]
[[191 357]
 [157 355]
 [212 247]
 [990 364]]
[[714 257]
 [725 225]
 [693 224]
 [771 184]]
[[1108  471]
 [1092  430]
 [1066  454]
 [ 996  362]]
[[278 272]
 [267 234]
 [231 254]
 [245 153]]
[[183 334]
 [192 321]
 [162 314]
 [224 243]]
[[723 264]
 [729 220]
 [695 225]
 [769 182]]
[[1122  483]
 [1104  434]
 [1075  457]
 [1006  370]]
[[326 320]
 [314 277]
 [282 299]
 [245 202]]
[[174 313]
 [187 314]
 [162 294]
 [242 229]]
[[761 289]
 [755 240]
 [725 253]
 [755 176]]
[[1132  474]
 [1107  427]
 [1081  456]
 [1002  368]]
[[345 336]
 [334 290]
 [302 316]
 [287 225]]
[[170 325]
 [186 314]
 [159 296]
 [243 228]]
[[789 315]
 [784 265]
 [746 282]
 [734 190]]
[[1162  462]
 [1120  416]
 [1103  458]
 [1009  375]]
[[410 333]
 [378 305]
 [364 336]
 [288 258]]
[[173 335]
 [191 320]
 [156 308]
 [237 231]]
[[802 336]
 [794 293]
 [762 312]
 [727 204]]
[[1171  452]
 [1131  403]
 [1109  443]
 [1010  3

 [902 362]]
[[435 174]
 [455 199]
 [463 178]
 [520 246]]
[[537  99]
 [537 146]
 [559 145]
 [577 234]]
[[530 137]
 [505 134]
 [517 157]
 [400 169]]
[[865 267]
 [876 285]
 [898 259]
 [912 361]]
[[389 189]
 [411 218]
 [421 188]
 [516 250]]
[[531  95]
 [521 143]
 [552 143]
 [573 227]]
[[618 156]
 [585 143]
 [585 166]
 [454 151]]
[[799 267]
 [830 288]
 [851 260]
 [923 341]]
[[311 189]
 [346 212]
 [346 184]
 [459 235]]
[[520  83]
 [511 138]
 [547 131]
 [562 218]]
[[651 169]
 [617 145]
 [617 174]
 [507 150]]
[[762 241]
 [794 271]
 [802 239]
 [890 296]]
[[234 197]
 [257 216]
 [260 185]
 [385 225]]
[[521  81]
 [509 128]
 [549 125]
 [553 206]]
[[671 143]
 [638 146]
 [654 167]
 [519 161]]
[[717 253]
 [759 268]
 [759 243]
 [860 287]]
[[160 209]
 [199 218]
 [198 192]
 [316 221]]
[[519  83]
 [507 122]
 [542 129]
 [544 187]]
[[702 141]
 [671 143]
 [685 174]
 [576 153]]
[[657 225]
 [675 249]
 [685 221]
 [785 272]]
[[146 218]
 [173 236]
 [180 207]
 [301 223]]
[[497  94]
 [493 143]
 [539 136]
 [552 203]

 [1104  370]]
[[428 359]
 [444 341]
 [421 327]
 [518 269]]
[[1270  200]
 [1233  184]
 [1226  225]
 [1105  222]]
[[596 135]
 [573 148]
 [593 170]
 [489 191]]
[[1197  227]
 [1160  250]
 [1192  273]
 [1085  356]]
[[396 373]
 [423 362]
 [401 342]
 [490 273]]
[[1223  222]
 [1182  200]
 [1173  235]
 [1060  225]]
[[602 131]
 [575 148]
 [595 173]
 [487 191]]
[[1225  215]
 [1173  242]
 [1194  270]
 [1085  336]]
[[370 360]
 [391 359]
 [380 331]
 [479 280]]
[[1181  221]
 [1156  205]
 [1153  241]
 [1047  224]]
[[595 131]
 [576 143]
 [593 169]
 [487 191]]
[[1266  239]
 [1212  234]
 [1216  273]
 [1098  305]]
[[389 348]
 [406 348]
 [387 325]
 [490 284]]
[[1167  162]
 [1135  172]
 [1160  197]
 [1043  228]]
[[597 132]
 [578 146]
 [593 169]
 [494 190]]
[[1273  241]
 [1260  222]
 [1264  259]
 [1139  289]]
[[414 375]
 [427 359]
 [399 353]
 [487 284]]
[[1156  124]
 [1120  173]
 [1164  181]
 [1044  236]]
[[603 143]
 [572 148]
 [585 174]
 [487 193]]
[[1269  238]
 [1233  225]
 [1246  267]
 [1130  291]]
[[418 

[[155 332]
 [150 377]
 [180 360]
 [235 435]]
[[809 499]
 [833 524]
 [840 497]
 [951 518]]
[[1015  260]
 [ 991  267]
 [1019  296]
 [ 896  363]]
[[799 296]
 [768 282]
 [771 308]
 [647 294]]
[[214 348]
 [180 363]
 [219 373]
 [228 459]]
[[817 476]
 [837 507]
 [850 487]
 [955 520]]
[[1082  243]
 [1034  252]
 [1063  283]
 [ 944  335]]
[[872 284]
 [843 266]
 [843 293]
 [720 293]]
[[231 346]
 [198 363]
 [227 366]
 [218 462]]
[[755 462]
 [792 489]
 [800 459]
 [910 513]]
[[1139  205]
 [1087  215]
 [1111  248]
 [ 978  298]]
[[922 321]
 [902 283]
 [889 314]
 [769 286]]
[[236 293]
 [188 310]
 [227 325]
 [197 425]]
[[675 421]
 [692 458]
 [712 430]
 [816 487]]
[[1185  229]
 [1125  222]
 [1142  258]
 [ 998  287]]
[[989 377]
 [979 342]
 [947 366]
 [848 301]]
[[260 228]
 [217 250]
 [248 265]
 [215 363]]
[[593 413]
 [623 448]
 [627 404]
 [737 461]]
[[1199  262]
 [1160  242]
 [1163  279]
 [1003  294]]
[[1029  413]
 [1029  384]
 [1003  404]
 [ 906  320]]
[[259 160]
 [222 198]
 [259 210]
 [222 303]]
[[524 4

 [194 177]]
[[193 338]
 [242 351]
 [234 318]
 [344 320]]
[[1274  322]
 [1264  286]
 [1249  334]
 [1143  284]]
[[231 212]
 [263 239]
 [284 200]
 [358 232]]
[[ 86  83]
 [105 146]
 [136 121]
 [222 200]]
[[190 279]
 [210 315]
 [229 294]
 [332 327]]
[[1266  334]
 [1230  287]
 [1205  317]
 [1108  272]]
[[234 197]
 [269 236]
 [286 195]
 [358 229]]
[[101 111]
 [128 160]
 [143 125]
 [245 211]]
[[157 246]
 [176 293]
 [197 272]
 [287 335]]
[[1146  348]
 [1167  310]
 [1130  315]
 [1061  253]]
[[242 195]
 [273 232]
 [294 194]
 [366 234]]
[[149 181]
 [173 193]
 [170 155]
 [259 210]]
[[203 224]
 [186 269]
 [222 265]
 [276 334]]
[[1087  375]
 [1125  342]
 [1094  331]
 [1073  232]]
[[255 191]
 [291 221]
 [297 193]
 [389 243]]
[[166 193]
 [187 200]
 [186 164]
 [280 211]]
[[214 193]
 [198 245]
 [235 246]
 [262 335]]
[[1041  372]
 [1098  352]
 [1067  325]
 [1109  258]]
[[290 229]
 [331 241]
 [322 205]
 [418 238]]
[[183 267]
 [197 229]
 [167 222]
 [269 186]]
[[250 210]
 [205 246]
 [249 266]
 [263 329]]
[[1

[[1188  421]
 [1156  449]
 [1185  473]
 [1064  510]]
[[523 525]
 [494 493]
 [477 524]
 [424 435]]
[[327 520]
 [339 489]
 [308 489]
 [338 379]]
[[542 104]
 [518 150]
 [561 157]
 [477 239]]
[[1175  345]
 [1153  387]
 [1197  390]
 [1125  490]]
[[580 542]
 [568 499]
 [541 521]
 [456 468]]
[[320 504]
 [332 487]
 [303 483]
 [335 382]]
[[542 107]
 [516 150]
 [551 160]
 [477 235]]
[[1178  300]
 [1153  352]
 [1201  349]
 [1126  444]]
[[585 562]
 [585 507]
 [552 521]
 [514 463]]
[[284 517]
 [307 501]
 [283 486]
 [344 393]]
[[531  86]
 [509 138]
 [547 141]
 [504 221]]
[[1163  266]
 [1144  311]
 [1182  315]
 [1139  418]]
[[569 573]
 [589 524]
 [544 527]
 [552 472]]
[[221 517]
 [243 514]
 [229 487]
 [315 414]]
[[534  78]
 [504 131]
 [548 142]
 [509 211]]
[[1156  197]
 [1142  234]
 [1182  231]
 [1142  359]]
[[535 571]
 [566 521]
 [527 516]
 [542 456]]
[[163 509]
 [180 510]
 [173 487]
 [291 449]]
[[1157  133]
 [1130  176]
 [1180  183]
 [1140  290]]
[[555  91]
 [509 126]
 [554 145]
 [516 201]]
[[517 5

 [229 150]]
[[659 215]
 [627 190]
 [621 217]
 [509 218]]
[[879 506]
 [850 449]
 [822 486]
 [765 406]]
[[1252  432]
 [1197  396]
 [1188  435]
 [1043  373]]
[[245 322]
 [241 273]
 [204 291]
 [224 194]]
[[751 243]
 [724 212]
 [719 242]
 [606 224]]
[[888 500]
 [862 449]
 [831 483]
 [778 406]]
[[1271  455]
 [1229  414]
 [1211  455]
 [1075  380]]
[[243 352]
 [236 314]
 [203 322]
 [217 219]]
[[759 229]
 [757 212]
 [747 252]
 [652 231]]
[[874 518]
 [854 461]
 [822 487]
 [775 404]]
[[1257  465]
 [1230  420]
 [1204  448]
 [1073  377]]
[[263 383]
 [249 351]
 [215 365]
 [229 250]]
[[750 229]
 [734 215]
 [740 242]
 [637 229]]
[[872 496]
 [844 449]
 [814 485]
 [776 408]]
[[1259  487]
 [1230  432]
 [1198  468]
 [1078  391]]
[[274 386]
 [259 370]
 [235 384]
 [211 290]]
[[788 200]
 [761 193]
 [772 218]
 [651 229]]
[[886 470]
 [854 434]
 [826 476]
 [778 410]]
[[1237  510]
 [1218  454]
 [1181  480]
 [1080  387]]
[[274 391]
 [259 366]
 [231 384]
 [217 290]]
[[816 159]
 [783 172]
 [814 193]
 [697 232]]
[[8

In [48]:
# Creating YOLO training labels(.txt)
lis = np.zeros((len(data), 4, 5))
for i in range(len(data)):
    for j in range(4):
        ind = i*4+j
        curlis = lis[i][j]
        curlis[0] = 0
        curlis[1] = (bbox[ind][0][0] + bbox[ind][0][2])/ 2 / 1280
        curlis[2] = (bbox[ind][0][1] + bbox[ind][0][3])/ 2 / 720
        curlis[3] = (bbox[ind][0][2] - bbox[ind][0][0]) / 1280
        curlis[4] = (bbox[ind][0][3] - bbox[ind][0][1]) / 720

In [67]:
import sys
orig_stdout = sys.stdout

for i in range(int(0.8*len(data))):
    if(i!=152):
        filename = './traintxt/'+data[i]['filename'][0:4] + '.txt'
        f = open(filename, 'w')
        sys.stdout = f
        for j in range(4):
            tmp = lis[i][j]
            print("%.0d %.6f %.6f %.6f %.6f " % (tmp[0], tmp[1], tmp[2], tmp[3], tmp[4]))

sys.stdout = orig_stdout
f.close()

#        print()

In [69]:
# train.txt

orig_stdout = sys.stdout
f = open('./traintxt/train.txt', 'w')
sys.stdout = f

for i in range(int(len(data)*0.8)):
    if(i!=152):
        ind = i*4
        filename = data[i]['filename'][0:4]+'.jpg'
        print('./build/darknet/x64/data/obj/'+filename)
    
sys.stdout = orig_stdout
f.close()

In [57]:
int(len(data)*0.8)

886

In [77]:
f.close()

In [78]:
f = h5py.File('annot_data1010.h5', "r")

In [79]:
for name in f:
    print(name)

bndbox
imgname
part


In [195]:
f.close()

In [200]:
x = ((2,3),(3,4))

In [201]:
for pair in x:
    dim0, dim1 = pair