In [1]:
import h5py
import numpy as np
f = h5py.File("mytestfile.hdf5", "w")
dset = f.create_dataset("mydataset", (100,), dtype='i')

In [3]:
f.keys()

KeysView(<HDF5 file "mytestfile.hdf5" (mode r+)>)

In [17]:
dset.name

'/mydataset'

In [18]:
f.name

'/'

In [19]:
f = h5py.File('mydataset.hdf5', 'r+')

In [20]:
grp = f.create_group("subgroup")

ValueError: Unable to create group (name already exists)

In [21]:
dset2 = grp.create_dataset("another_dataset", (50,), dtype='f')

In [22]:
dset3 = f.create_dataset('subgroup2/dataset_three', (10,), dtype='i')

In [23]:
dataset_three = f['subgroup2/dataset_three']

In [28]:
for name in f:
    print(name)

ds1
subgroup
subgroup2


In [58]:
dsetq = f.create_dataset('dsq', (10,), dtype='i')


In [68]:
for i in range(10):
    dsetq[i] = i+1
dsetq.shape

(10,)

In [30]:
file = h5py.File("annot_coco.h5", "r")

In [32]:
file.keys()

KeysView(<HDF5 file "annot_coco.h5" (mode r)>)

In [33]:
for k in file.keys():
    print(k)

bndbox
imgname
part


In [34]:
for name in file:
    print(name)

bndbox
imgname
part


In [62]:
parts = file['part']

In [63]:
parts.shape

(144213, 17, 2)

In [52]:
p = parts[2565]
print(p)

[[497 222]
 [502 218]
 [493 218]
 [509 217]
 [  0   0]
 [524 237]
 [484 237]
 [  0   0]
 [473 270]
 [  0   0]
 [464 304]
 [522 298]
 [486 298]
 [531 319]
 [468 317]
 [523 353]
 [484 385]]


In [44]:
imgn = file['imgname']
imgn[225]

array([ 48.,  48.,  48.,  48.,  48.,  48.,  49.,  48.,  57.,  50.,  55.,
        55.,  46., 106., 112., 103.])

In [51]:
imgn[399]

array([ 48.,  48.,  48.,  48.,  48.,  48.,  49.,  51.,  49.,  54.,  50.,
        49.,  46., 106., 112., 103.])

In [69]:
from utils.dataset import coco
train_dataset = coco.Mscoco(train=True)
val_dataset = coco.Mscoco(train=False)

ModuleNotFoundError: No module named 'utils'

In [70]:
len(imgn)

144213

In [75]:
x = [x for x in range(10)]
x[-2:]

[8, 9]

In [79]:
print("%.2f kg" % x[0])

0.00 kg
